# fly.toml app configuration file generated for fly-polymarket-proxy-v01nnq on 2026-06-02T22:46:11Z
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'fly-polymarket-proxy-v01nnq'
primary_region = 'ams'

[build]

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 1

[[vm]]
  cpu_kind = 'shared'
  cpus = 1
  memory_mb = 256
