# fly.toml app configuration file generated for fly-polymarket-proxy-btor4w on 2026-05-04T16:11:34Z
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'fly-polymarket-proxy-btor4w'
primary_region = 'arn'

[build]

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 1

[[vm]]
  cpu_kind = 'shared'
  cpus = 1
  memory_mb = 256
